# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RMApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RMApp
  pod 'SDWebImageSwiftUI'

  target 'RMAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RMAppUITests' do
    # Pods for testing
  end

end
